@startuml
skinparam defaultTextAlignment center

!include <awslib/AWSCommon>
!include <awslib/AWSSimplified.puml>
!include <awslib/Compute/all.puml>
!include <awslib/ManagementAndGovernance/all.puml>
!include <awslib/DeveloperTools/all.puml>
!include <awslib/MigrationAndTransfer/all.puml>
!include <awslib/General/all.puml>
!include <awslib/GroupIcons/all.puml>
!include <awslib/NetworkingAndContentDelivery/all.puml>

title: <size:20>Minio Proxy OVA</size>

CloudWatch(download_ova,                "\nDownload OVA" ," ")
TraditionalServer(icap_ova,             "\nICAP Server OVA" ," ")
ServerContents(minio_ova,               "\nMinio Server OVA" ," ")
VMwareCloudOnAWS(virtual_box,           "\nVirtualBox" ," ")
DeveloperTools(settings,                "\nSettings" ,"")
ServerMigrationService(icap_server,     "\nMinio Proxy VM" ," ")
User(user,                              "\nUser" ," ")
GlobalAccelerator(browser,              "\nBrowser" ," ")
CloudFormation(minio_server,            "\nMProxied Minio Server" ," ")
User(users,                             "\nUser" ," ")

icap_ova          ->       virtual_box   :Download/Start
minio_ova         -up->    virtual_box   :Download/Start
download_ova      -->      virtual_box   :Open and Import
virtual_box       ->       settings      :Verify/Configure
settings          ->       icap_server   :Start
user              -->      icap_server   :Login
icap_server       -->      browser       :Open
browser           -->      minio_server  :Access
users             ->       minio_server  :Login

@enduml
